[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
binary-heap-plus = "0.5.0"
gat-lending-iterator = "0.1.6"
gcd = "2.3.0"
itertools = "0.13.0"
regex = "1.11.1"
tqdm = "0.7.0"
